version: '3'

services:
  postgres-server:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=servey
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=servey_db

  app: &app
    image: grepp/node-webapp:1.0.0
    tmpfs:
      - /tmp

  node: &node
    <<: *app
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
      - public:/app/server/src/public
      - build:/app/server/build
      - client_node_modules:/app/client/node_modules
      - server_node_modules:/app/server/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres-server

  shell:
    <<: *node
    command: /bin/bash
    ports:
      - '5000:5000'

  server:
    <<: *node
    command: yarn run dev
    ports:
      - '5000:5000'

volumes:
  pgdata:
  node_modules:
  public:
  build:
  client_node_modules:
  server_node_modules:
