# Generated by Django 2.1.3 on 2018-11-10 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('admin_id', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=256)),
                ('salt', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Servey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServeyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('servey_name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServeyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('YN', 'YesorNo'), ('SI', 'Single'), ('MU', 'Mutiple')], default='YN', max_length=2)),
                ('order', models.IntegerField()),
                ('servey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serveies.Servey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServeyQuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('servey_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serveies.ServeyQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='ServeyQuestionAnswerItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('servey_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serveies.ServeyQuestion')),
            ],
        ),
        migrations.AddField(
            model_name='serveyquestionanswer',
            name='servey_question_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serveies.ServeyQuestionAnswerItem'),
        ),
    ]
