# Generated by Django 2.1.3 on 2018-11-10 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serveies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServeyPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('servey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serveies.Servey')),
            ],
        ),
        migrations.DeleteModel(
            name='ServeyHistory',
        ),
        migrations.RemoveField(
            model_name='serveyquestionanswer',
            name='servey_question',
        ),
        migrations.RemoveField(
            model_name='serveyquestionanswer',
            name='servey_question_item',
        ),
        migrations.DeleteModel(
            name='ServeyQuestionAnswer',
        ),
        migrations.AddField(
            model_name='serveyquestionansweritem',
            name='answer',
            field=models.ManyToManyField(to='serveies.ServeyPublication'),
        ),
    ]
